ecotest/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls' ,namespace='product')),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name='product'

urlpatterns=[
    path('',views.index, name='Home'),
    path('<int:id>',views.product_detial,name='products_details' ),
    path('done',views.done, name='done'),
    path('conditions_general/',views.conditions,name='conditions'),
    path('contactus/',views.contact,name='contact'),
    path('private_policy/',views.private,name='private')
]

products/models.py
from django.db import models

# Create your models here.
class Products(models.Model):
    name = models.CharField(max_length=300)
    content = models.TextField()
    rating = models.CharField(max_length=100)
    price = models.FloatField()
    url=models.CharField(max_length=300)
    image=models.ImageField(null=True, blank=True ,upload_to='photo/%y/%m/%d')
    image1=models.ImageField(null=True, blank=True ,upload_to='photo/%y/%m/%d')
    image2=models.ImageField(null=True, blank=True, upload_to='photo/%y/%m/%d')
    image3=models.ImageField(null=True, blank=True,upload_to='photo/%y/%m/%d')
    image4=models.ImageField(null=True, blank=True,upload_to='photo/%y/%m/%d')
    image5=models.ImageField(null=True, blank=True,upload_to='photo/%y/%m/%d')

    def __str__(self):
       return self.name    
    

class Email(models.Model):
   email=models.CharField(max_length=50)
   def __str__(self):
      return self.email
         

products/views.py
from django.shortcuts import render,redirect
from products.models import Products,Email

import json

def index(request):
    if request.method == 'POST':
        email=request.POST.get('email')
        data=Email(email=email)
        data.save() 
        return redirect('/done')   
    return render(request, 'index.html', {'pro' : Products.objects.all()})

def done(request):
    return render(request, 'done_demande.html', {'done':'done'})

def product_detial(request , id):
    product_detail=Products.objects.get(id=id)
    if request.method == 'POST':
        email=request.POST.get('email')
        data=Email(email=email)
        data.save() 
        return redirect('/done') 
      
    return render(request, 'products_details.html',{'prod':product_detail, 'pro':Products.objects.all()})

def conditions(request):
    return render(request,'conditions_general.html' , {'conditions':'conditions'})

def contact(request):
    return   render(request,'contact_us.html',{'contact':'contact'})

def private(request):
    return render(request,'private_policy.html',{'private':'private'}) 



    

templates/contact_us.html
{% load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link rel="stylesheet" href="{%static 'css/done_commande.css'%}">
    <title>ecotest</title>
  </head>
  <body>
   <div class="center"> <div class="myborder">
        <p class="text-success" >لقد تم ارسال بنجاح</p>
        <div><img src="{% static 'img/done.png'%}" alt="done"></div>
        <a href="{% url 'product:Home' %}"> <button class="btn btn-outline-primary"> رجوع الى صفحة الرئيسية </button></a>    
    </div>
  </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/done_demande.html
{% load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link rel="stylesheet" href="{%static 'css/done_commande.css'%}">
    <title>ecotest</title>
  </head>
  <body>
   <div class="center"> <div class="myborder">
        <p class="text-success" >لقد تم طلب بنجاح</p>
        <div><img src="{% static 'img/done.png'%}" alt="done"></div>
        <a href="{% url 'product:Home' %}"> <button class="btn btn-outline-primary"> رجوع الى صفحة الرئيسية </button></a>    
    </div>
  </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>amaship</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="">AMASHIP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link downline" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
       
     
      </ul>
     
    </div>
 
  </nav>

<div class="testcenter">
  <div class="container">
    
        <div class="row center-row">
          {%for product in pro %}
            <div class=" mr-2 mt-5">
                <div class="card" style="width: 18rem;">
                  {%if product.image%}
                   <a href="{%url 'product:products_details' product.id%}"><img class="productimg card-img-top imgcard" src="{{product.image.url}}" alt="Card image cap"></a>
                

                  {% endif%}
                  <div class="card-body">
                    <p class="card-title titlecard">{{product.name}} </p>
                     <h5 class="card-title price">{{product.price}}$  </h5>
                     <p class="card-text"> rating in amazon: {{product.rating}} <img class="star" src="{% static 'img/start.png' %}"></p>
          
                     
                      <div class="choisse">
                     <a href="{{product.url}}" target="_blank" class="btn btn-outline-primary mr-3">GO to amazon</a>
                      <a href="{%url 'product:products_details' product.id%}" class="categoryclick btn btn-outline-primary ml-3">view</a>
                    </div>
                    </div>
                  </div>
             </div>
      
            {% endfor%}
          
             </div>
        </div>    
             
        </div>
<footer>
  <div class="amaship">AMASHIP</div>
  <div class="last">
    <div class="lasttitle"><div> STAY ONLINE WITH US  </div>
      <p> GET NOTIFICATIONS FROM YOUR EMAIL  </p>
    </div>
    <form class="email" method="post">
      <div class="form-group">
         {%csrf_token %}
        <input type="email" class="form-control mr-5" required name="email" placeholder=" ENTER YOUR ADRESSEMAIL  ">
      </div>
      
      
      <input type="submit" class="btn btn-primary ml-5 mr-5"  value="submit">
    </form>
   </div> 
   

</footer>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
<style >
  .choisse{
    display: flex;
    justify-content: center;

  }
  .star{
    width: 25px;
  }
  .titlecard{
    font-weight: 500;
  }
.card{
    margin-top: 30px;
  }
.centerrow{
  display: flex!important;
  justify-content: center;

}  
.price{
  
  font-size: large;
  font-weight: 700;

}
.amaship{
        margin-top: 60px;
        background-color: #283647;
        padding: 5px 0;
        text-align: center;
        color: aliceblue;
       }
       .email{
                display: flex;
      
                flex-direction: column;
                justify-content: center;
              }
              .last{
                color: aliceblue;
                background: #232F3E;
                padding: 10px 0;
              }
              .lasttitle div{
                
                text-align: center;
                font-size: 25px;
                font-family: italic;
              }
              .lasttitle p{
                font-size: 13px;
                text-align: center;
              }
              div ul li a{
                position: relative;
              }
      div ul li a::before{
        position: absolute!important;
         content: '';
         left: 0;
         background-color: blue;
         width: 0;
         height: 3px;
         bottom: 4px;
         transition: 0.6s;
         
      }        
      div ul li a:hover::before{
         width: 100%;
      }
      .productimg{
              aspect-ratio: 2/2!important;
              object-fit: contain!important;
             }
             .center-row{
    display: flex!important;
    justify-content: center;
    margin-bottom: 10px;
}


</style>

templates/products_details.html
{% load static %}
<!doctype html>
<html  lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/product.css'%}">
    <title>AMASHIP</title>
  </head>
  <body>
 
  
  
 
  
  
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{%url 'product:Home'%}">amaship</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item ">
            <a class="nav-link downline" href="{% url 'product:Home'%}">Home <span class="sr-only">(current)</span></a>
          </li>
        
       
       
        </ul>
       
      </div>
   
    </nav>
      
<div class="container ">
    <div class="row " style="margin-top: 30px;">
        <div class="col-md-6">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  {%if prod.image %}
                  <div class="carousel-item active">
                    <img class="d-block w-100" src="{{prod.image.url}}" alt="First slide">
                  </div>
                  {%endif%}
                  {%if prod.image1 %}
                  <div class="carousel-item">
                    <img class="d-block w-100" src="{{prod.image1.url}}" alt="First slide">
                  </div>
                  {%endif%}
                  {%if prod.image2 %}
                  <div class="carousel-item ">
                    <img class="d-block w-100" src="{{prod.image2.url}}" alt="First slide">
                  </div>
                  {%endif%}
                  {%if prod.image3 %}
                  <div class="carousel-item ">
                    <img class="d-block w-100" src="{{prod.image3.url}}" alt="First slide">
                  </div>
                  {%endif%}
                  {%if prod.image4 %}
                  <div class="carousel-item">
                    <img class="d-block w-100" src="{{prod.image4.url}}" alt="First slide">
                  </div>
                  {%endif%}
                  {%if prod.image5 %}
                  <div class="carousel-item ">
                    <img class="d-block w-100" src="{{prod.image5.url}}" alt="First slide">
                  </div>
                  {%endif%}
                 
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only ">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only ">Next</span>
                </a>
              </div>
        </div> 
    
    <div class="col-md-6" >
       
         <div class="tilteofproducte">
                <h1 class="name">{{prod.name}}</h1>
                <h1 class="price"> Price: {{prod.price}}$</h1>
                <p  class="content">{{prod.content}}</p>

              </div>
                <!--customer info-->
                <div class="amazonbutton">
                <a href="{{prod.url}}" target="_blank" class="btn btn-outline-primary ">GO to amazon</a></div>
            
    
 

    </div></div></div>
      


    <footer>
      <div class="amaship">AMASHIP</div>
      <div class="last">
        <div class="lasttitle"><div> STAY ONLINE WITH US  </div>
          <p> GET NOTIFICATIONS FROM YOUR EMAIL  </p>
        </div>
        <form class="email" method="post">
          <div class="form-group">
             {%csrf_token %}
            <input type="email" class="form-control mr-5" required name="email" placeholder=" ENTER YOUR ADRESSEMAIL  ">
          </div>
          
          
          <input type="submit" class="btn btn-primary ml-5 mr-5"  value="submit">
        </form>
       </div> 
       
    
    </footer>
<style>
   div ul li a{
                position: relative;
              }
      div ul li a::before{
        position: absolute!important;
         content: '';
         left: 0;
         background-color: blue;
         width: 0;
         height: 3px;
         bottom: 4px;
         transition: 0.6s;
         
      }        
      div ul li a:hover::before{
         width: 100%;
      }
 
  .amazonbutton{
    display: flex;
    justify-content:center ;
  }
  .amaship{
        margin-top: 60px;
        background-color: #283647;
        padding: 5px 0;
        text-align: center;
        color: aliceblue;
       }
       .email{
                display: flex;
      
                flex-direction: column;
                justify-content: center;
              }
              .last{
                color: aliceblue;
                background: #232F3E;
                padding: 10px 0;
              }
              .lasttitle div{
                
                text-align: center;
                font-size: 25px;
                font-family: italic;
              }
              .lasttitle p{
                font-size: 13px;
                text-align: center;
              }

 



 </style> 


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
     <script src="{% static 'js/product.js'%}"></script>
  </body>
</html>